### PR TITLE
Test against multiple python versions

### PR DESCRIPTION
**Pull request by dlstadther**
Check for Py3 compatibility with two most recent Python3 versions.

If successful, setup.py metadata will need to be updated.

### CODE REVIEW

**Comment by atharvai** [comment]
packaged and available on Test Pypi for checks: https://test.pypi.org/project/luigi-monitor/
@dlstadther can you check and confirm? I don't have 3.7 environment.

**Comment by dlstadther** [comment]
```shell
$ pyenv global 3.7.0
$ virtualenv -p python3 ~/venv/py37-monitor
$ ~/venv/py37-monitor/bin/pip install luigi
$ ~/venv/py37-monitor/bin/pip install --index-url https://test.pypi.org/project/ luigi-monitor==1.1.4
$ ~/venv/py37-monitor/bin/python test_luigi_monitor.py
# successfully output to slack
```

**Review by atharvai — APPROVED** [review]
Looks good to merge, can you add a brief CHANGELOG.md entry for 1.1.4?

**Comment by dlstadther** [comment]
Thanks!

**Comment by atharvai** [comment]
available on prod pypi https://pypi.org/project/luigi-monitor/1.1.4/

**Pull request merged**
