### PR TITLE
enhanced message

### PR DESCRIPTION
**Pull request by boferri**
* added emojis for success or fail state
* added hostname
* added list of successful ran tasks

### CODE REVIEW

**Comment by atharvai** [comment]
Can you make the PR a bit more descriptive? Maybe add examples of what the enhanced messages look like? It's hard to quickly understand what the objective of the PR is and why we need it. I'll review soon

**Comment by boferri** [comment]
@atharvai I fixed the tests. are these examples descriptive?

**Comment by boferri** [comment]
ping @atharvai

**Comment by atharvai** [comment]
https://test.pypi.org/project/luigi-monitor/ can you verify the latest version on test pypi?

**Comment by boferri** [comment]
looks good from my point of view ;)

**Comment by atharvai** [comment]
available on prod pypi https://pypi.org/project/luigi-monitor/

**Pull request merged**
